Resources:
  AccountTopicSubscriberQueue:
    DeletionPolicy: Retain
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 604800
      QueueName: "Account-TopicSubscriber-${opt:stage, self:custom.defaultStage}-${self:service.name}-Queue"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt AccountTopicSubscriberDeadLetterQueue.Arn
        maxReceiveCount: 25
      VisibilityTimeout: 120

  AccountTopicSubscriberQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "allow-sns-messages"
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt
              - AccountTopicSubscriberQueue
              - Arn
            Action: "SQS:SendMessage"
            Condition:
              ArnEquals:
                "aws:SourceArn": 'arn:aws:sns:eu-central-1:${self:custom.ProductBackendAccounts.${opt:stage, self:custom.defaultStage}.AccountId}:ext-sf-account-${opt:stage, self:custom.defaultStage}'
      Queues:
        - Ref: AccountTopicSubscriberQueue

  AccountTopicSubscriberDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: "Account-TopicSubscriber-${opt:stage, self:custom.defaultStage}-${self:service.name}-Queue-dl-queue"


  AccountTopicSubscriberQueueSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: 'arn:aws:sns:eu-central-1:${self:custom.ProductBackendAccounts.${opt:stage, self:custom.defaultStage}.AccountId}:ext-sf-account-${opt:stage, self:custom.defaultStage}'
      Endpoint: !GetAtt
        - AccountTopicSubscriberQueue
        - Arn
      Protocol: sqs
      RawMessageDelivery: "false"