Resources:
  BookingTopicSubscriberQueue:
    DeletionPolicy: Retain
    Type: "AWS::SQS::Queue"
    Properties:
      MessageRetentionPeriod: 604800
      QueueName: "Booking-TopicSubscriber-${opt:stage, self:custom.defaultStage}-${self:service.name}-Queue"
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt BookingTopicSubscriberDeadLetterQueue.Arn
        maxReceiveCount: 25
      VisibilityTimeout: 120

  BookingTopicSubscriberQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "allow-sns-messages"
            Effect: Allow
            Principal: "*"
            Resource: !GetAtt
              - BookingTopicSubscriberQueue
              - Arn
            Action: "SQS:SendMessage"
            Condition:
              ArnEquals:
                "aws:SourceArn": 'arn:aws:sns:eu-central-1:${self:custom.ProductBackendAccounts.${opt:stage, self:custom.defaultStage}.AccountId}:ext-sf-booking-${opt:stage, self:custom.defaultStage}'
      Queues:
        - Ref: BookingTopicSubscriberQueue

  BookingTopicSubscriberDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: "Booking-TopicSubscriber-${opt:stage, self:custom.defaultStage}-${self:service.name}-Queue-dl-queue"


  BookingTopicSubscriberQueueSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: 'arn:aws:sns:eu-central-1:${self:custom.ProductBackendAccounts.${opt:stage, self:custom.defaultStage}.AccountId}:ext-sf-booking-${opt:stage, self:custom.defaultStage}'
      Endpoint: !GetAtt
        - BookingTopicSubscriberQueue
        - Arn
      Protocol: sqs
      RawMessageDelivery: "false"